//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KIEMTHESDK.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChatData
    {
        public int ID { get; set; }
        public string ChatID { get; set; }
        public string FromRoleName { get; set; }
        public string ToRoleName { get; set; }
        public Nullable<int> Channel { get; set; }
        public Nullable<System.DateTime> ChatTime { get; set; }
        public string FileName { get; set; }
    }
}
