//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KIEMTHESDK.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Config
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> StartKM { get; set; }
        public Nullable<System.DateTime> EndKM { get; set; }
        public Nullable<double> NormalRate { get; set; }
        public Nullable<double> KMRate { get; set; }
    }
}
