//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KIEMTHESDK.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class CsmLogin
    {
        public int ID { get; set; }
        public string LoginName { get; set; }
        public string Password { get; set; }
        public Nullable<int> Premission { get; set; }
        public Nullable<System.DateTime> RegTime { get; set; }
    }
}
