//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KIEMTHESDK.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class GiftCodeLog
    {
        public int ID { get; set; }
        public string Code { get; set; }
        public Nullable<int> ActiveRole { get; set; }
        public Nullable<System.DateTime> ActiveTime { get; set; }
        public string CodeType { get; set; }
        public Nullable<int> ServerID { get; set; }
    }
}
