//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KIEMTHESDK.Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class KiemTheDbEntities : DbContext
    {
        public KiemTheDbEntities()
            : base("name=KiemTheDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ChatData> ChatDatas { get; set; }
        public virtual DbSet<Config> Configs { get; set; }
        public virtual DbSet<CsmLogin> CsmLogins { get; set; }
        public virtual DbSet<GiftCodeLog> GiftCodeLogs { get; set; }
        public virtual DbSet<GiftCode> GiftCodes { get; set; }
        public virtual DbSet<KTCoin> KTCoins { get; set; }
        public virtual DbSet<LoginTable> LoginTables { get; set; }
        public virtual DbSet<LogsTran> LogsTrans { get; set; }
        public virtual DbSet<NewsTable> NewsTables { get; set; }
        public virtual DbSet<RechageLog> RechageLogs { get; set; }
        public virtual DbSet<ServerList> ServerLists { get; set; }
        public virtual DbSet<ServerListsIo> ServerListsIos { get; set; }
        public virtual DbSet<TokenManager> TokenManagers { get; set; }
    }
}
