//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KIEMTHESDK.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class KTCoin
    {
        public int ID { get; set; }
        public Nullable<int> UserID { get; set; }
        public string UserName { get; set; }
        public Nullable<int> KCoin { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
    }
}
