//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KIEMTHESDK.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoginTable
    {
        public int ID { get; set; }
        public string LoginName { get; set; }
        public string Password { get; set; }
        public string Phone { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> ActiveRoleID { get; set; }
        public string ActiveRoleName { get; set; }
        public string FullName { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> TokenTimeExp { get; set; }
        public string AccessToken { get; set; }
        public string Note { get; set; }
        public Nullable<int> LastServerLogin { get; set; }
        public Nullable<System.DateTime> LastLoginTime { get; set; }
        public string LastIPLogin { get; set; }
        public Nullable<double> Commission { get; set; }
    }
}
