//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KIEMTHESDK.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogsTran
    {
        public int ID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> RoleID { get; set; }
        public string RoleName { get; set; }
        public Nullable<int> ServerID { get; set; }
        public Nullable<int> Value { get; set; }
        public Nullable<System.DateTime> TimeTrans { get; set; }
        public Nullable<int> BeforeValue { get; set; }
        public Nullable<int> AfterValue { get; set; }
    }
}
