//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KIEMTHESDK.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class NewsTable
    {
        public int ID { get; set; }
        public string Catagory { get; set; }
        public string Title { get; set; }
        public string Context { get; set; }
        public Nullable<System.DateTime> DateTime { get; set; }
    }
}
