//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KIEMTHESDK.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class RechageLog
    {
        public int ID { get; set; }
        public Nullable<int> UserID { get; set; }
        public string UserName { get; set; }
        public Nullable<int> CoinValue { get; set; }
        public Nullable<int> BeforeCoin { get; set; }
        public Nullable<int> AfterCoin { get; set; }
        public Nullable<System.DateTime> RechageDate { get; set; }
        public string RechageType { get; set; }
        public string Pram_0 { get; set; }
        public string Pram_1 { get; set; }
        public string Pram_2 { get; set; }
        public Nullable<int> Pram_3 { get; set; }
        public string Messenger { get; set; }
        public Nullable<int> Status { get; set; }
        public string TransID { get; set; }
        public Nullable<int> ValueRechage { get; set; }
        public string ActionBy { get; set; }
    }
}
