//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KIEMTHESDK.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServerListsIo
    {
        public int ID { get; set; }
        public string strServerName { get; set; }
        public Nullable<int> nServerOrder { get; set; }
        public Nullable<int> nServerPort { get; set; }
        public Nullable<int> nStatus { get; set; }
        public string strURL { get; set; }
        public Nullable<int> nServerID { get; set; }
        public Nullable<int> nOnlineNum { get; set; }
        public Nullable<int> HttpServicePort { get; set; }
        public Nullable<System.DateTime> strMaintainStarTime { get; set; }
        public Nullable<System.DateTime> strMaintainTerminalTime { get; set; }
        public string strMaintainTxt { get; set; }
        public Nullable<int> isTestServer { get; set; }
    }
}
